feat: 🎸 add support for v8.2.0 v8.3.0 v9.1.0
ngworker/angular-versions-action pull request #2
Opened 2020-10-22 20:15 UTC by NachoVazquez

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ x ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ x ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Missing support for some minor version of Angular

Issue Number: 1

## What is the new behavior?

Adds supports for version 8.2.x, 8.3.x, 9.1.x of Angular.

## Does this PR introduce a breaking change?

```
[ ] Yes
[ x ] No
```

## Other information
Solves issues: #1

2020-10-23 07:53 UTC, LayZeeDK requested changes

2020-10-23 07:53 UTC, LayZeeDK commented on src/angular-versions.ts
> +  ],
There is no Angular 8.3, only Angular CLI 8.3.
```suggestion
```

2020-10-23 07:53 UTC, LayZeeDK commented on src/angular-versions.ts
> +        '@angular/cli': '~8.2.0',
Let's use the latest compatible CLI and builders
```suggestion
        '@angular-devkit/build-angular': '~0.803.0',
        '@angular-devkit/build-ng-packagr': '~0.803.0',
        '@angular/cli': '~8.3.0',
```

2020-10-23 07:53 UTC, LayZeeDK commented on README.md
> +- 8.3.x
There is no Angular 8.3, only Angular CLI 8.3.
```suggestion
```

2020-10-23 21:24 UTC, LayZeeDK approved these changes

2020-10-23 21:24 UTC, LayZeeDK commented
How do we bump the version number?

2020-10-24 03:14 UTC, NachoVazquez commented
> How do we bump the version number?

`yarn release`

One important thing to notice is that before a release is ready we have to build the actions and commit the dist files. I know it sounds weird but it is the way it is done because Github uses those files directly from the repo to deploy the action.

This can be useful

https://github.com/actions/toolkit/blob/master/docs/action-versioning.md
https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action

2020-10-24 11:32 UTC, LayZeeDK approved these changes

2020-10-24 16:11 UTC, merged